runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*)
  static_files: \1
  upload: /(.*)

- url: /(.*)/
  static_files: /\1/index.html
  upload: /.*/index.html

- url: /(.*)$
  static_files: /\1
  upload: /.*

#- url: /.*
#  script: main.app
#  secure: always
#  redirect_http_response_code: 301